'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawn}=require('node:child_process');
async function digest(file){const h=crypto.createHash('sha256');for await(const b of fs.createReadStream(file))h.update(b);return h.digest('hex');}
function command(mode,file,stage){return new Promise((resolve,reject)=>{const p=spawn(path.join(process.env.SystemRoot||'C:\\Windows','System32/WindowsPowerShell/v1.0/powershell.exe'),['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',path.join(__dirname,'backup-zip.ps1'),'-Mode',mode,'-File',file,'-Stage',stage],{windowsHide:true,stdio:['ignore','pipe','pipe']});let out='',err='';p.stdout.on('data',b=>{out+=b;if(out.length>16*1024*1024)p.kill()});p.stderr.on('data',b=>{if(err.length<1000)err+=b});p.on('error',reject);p.on('close',code=>code?reject(Error('تعذر '+(mode==='create'?'إنشاء':'قراءة')+' ملف ZIP: '+err.slice(0,250))):resolve(out));});}
async function create({file,stage,names,mode}){const files=[];for(const name of names)files.push({path:name,size:fs.statSync(path.join(stage,name)).size,sha256:await digest(path.join(stage,name))});fs.writeFileSync(path.join(stage,'backup-manifest.json'),JSON.stringify({format:'zain-zip',version:1,mode,createdAt:new Date().toISOString(),files}));await command('create',file,stage);}
async function extract({file,stage}){const info=JSON.parse(await command('inspect',file,stage));if(!info)return null;const m=info.manifest,{allowed,fixed}=require('./backup-worker.cjs');if(m.format!=='zain-zip'||m.version!==1||!['quick','full'].includes(m.mode)||!Array.isArray(m.files)||!m.files.length||m.files.length>20000)throw Error('بيان ZIP غير صالح');let total=0;const seen=new Set();for(const r of m.files){if(!allowed(r.path)||m.mode==='quick'&&!fixed.includes(r.path)||seen.has(r.path.toLowerCase())||!Number.isSafeInteger(r.size)||r.size<0||!/^[a-f0-9]{64}$/.test(r.sha256))throw Error('ملفات ZIP غير صالحة');seen.add(r.path.toLowerCase());total+=r.size;if(total>16*1024**3)throw Error('حجم ZIP يتجاوز الحد');}
const expected=new Map(m.files.map(r=>[r.path,r.size]));if(info.entries.length!==m.files.length+1)throw Error('ملفات ZIP إضافية');const entries=new Set();for(const e of info.entries){if(entries.has(e.name.toLowerCase()))throw Error('ملفات ZIP مكررة');entries.add(e.name.toLowerCase());if(e.name!=='backup-manifest.json'&&expected.get(e.name)!==e.size)throw Error('ملف ZIP غير متوقع');}
await command('extract',file,stage);for(const r of m.files)if(await digest(path.join(stage,r.path))!==r.sha256)throw Error('فشل التحقق من سلامة '+r.path);return {files:m.files.map(r=>r.path),mode:m.mode};}
module.exports={create,extract};
