'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),{spawn}=require('node:child_process');
module.exports=function({base,port,mainPort,authorize,allowedHost,onEvent=()=>{}}){
 const file=path.join(base,'data/broadcast.json'),output=path.join(base,'data/live-streams'),assets=path.join(base,'mubasher_assets'),jobs=new Map(),viewers=new Map();
 const statsFile=path.join(base,'data/broadcast-stats.json');let stats=fs.existsSync(statsFile)?JSON.parse(fs.readFileSync(statsFile,'utf8')):{};
 function trackViewer(req,id){const day=new Date().toISOString().slice(0,10),key=id+'|'+req.socket.remoteAddress,now=Date.now();for(const [k,t]of viewers)if(now-t>60000)viewers.delete(k);const fresh=!viewers.has(key);viewers.set(key,now);if(fresh){const row=stats[id]||(stats[id]={total:0,day,count:0});if(row.day!==day){row.day=day;row.count=0;}row.total++;row.count++;fs.writeFileSync(statsFile+'.tmp',JSON.stringify(stats));fs.renameSync(statsFile+'.tmp',statsFile);}}

 let state=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):{channels:[],iptv:[],file:[]},listening=false,error='';fs.mkdirSync(output,{recursive:true});
 const escape=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fail=(s,status=400)=>Object.assign(Error(s),{status});
 for(const table of ['iptv','file'])if(!Array.isArray(state[table]))state[table]=[];
 function save(next){fs.mkdirSync(path.join(base,'data/backups'),{recursive:true});if(fs.existsSync(file))fs.copyFileSync(file,path.join(base,'data/backups','broadcast-'+Date.now()+'.json'));fs.writeFileSync(file+'.tmp',JSON.stringify(next));fs.renameSync(file+'.tmp',file);state=next;}
 function validateSource(value){if(typeof value!=='string'||value.length>4096||/[\x00-\x1f]/.test(value))throw fail('مصدر البث غير صالح');if(/^[A-Za-z]:[\\/]/.test(value)||/^\\\\[^?.\\][^\\]*\\[^\\]+/.test(value))return value;let u;try{u=new URL(value);}catch{throw fail('اكتب رابط بث كامل أو مسار ملف فيديو');}if(!['http:','https:','rtsp:','udp:','rtp:'].includes(u.protocol))throw fail('نوع رابط البث غير مدعوم');return value;}
 async function stop(id){const job=jobs.get(id);if(job?.process){job.status='stopping';job.process.kill();await new Promise(resolve=>{const t=setTimeout(resolve,3000);job.process.once('exit',()=>{clearTimeout(t);resolve();});});}jobs.delete(id);if(job)onEvent('إيقاف بث القناة: '+(state.channels.find(c=>c.id===id)?.name||id),'warning');}
 async function start(id){const channel=state.channels.find(x=>x.id===id);if(!channel)throw fail('القناة غير موجودة',404);const existing=jobs.get(id);if(existing?.process&&['starting','running'].includes(existing.status))return {msg:'ok',is_ok:true};if([...jobs.values()].filter(x=>x.process).length>=4)throw fail('الحد الحالي أربع قنوات متزامنة',409);
 const exe=path.join(base,'runtime/ffmpeg/ffmpeg.exe');if(!fs.existsSync(exe))throw fail('ملف تشغيل البث FFmpeg غير موجود',503);
 const folder=path.join(output,id+'-'+crypto.randomUUID());fs.mkdirSync(folder,{recursive:true});const args=['-hide_banner','-nostdin','-loglevel','warning'];const src=validateSource(channel.source);if(/^[A-Za-z]:[\\/]|^\\\\/.test(src))args.push('-re','-stream_loop','-1');else if(/^https?:/i.test(src))args.push('-rw_timeout','15000000');args.push('-i',src,'-map','0:v:0?','-map','0:a:0?','-c:v','libx264','-preset','veryfast','-threads','2','-vf','scale=w=min(1280\\,iw):h=-2','-pix_fmt','yuv420p','-g','50','-sc_threshold','0','-c:a','aac','-b:a','128k','-f','hls','-hls_time','2','-hls_list_size','6','-hls_flags','delete_segments+independent_segments','-hls_segment_filename',path.join(folder,'segment-%08d.ts'),path.join(folder,'index.m3u8'));
 const child=spawn(exe,args,{windowsHide:true,shell:false,stdio:['ignore','ignore','pipe']});const job={process:child,status:'starting',folder,error:'',startedAt:Date.now()};jobs.set(id,job);
 child.stderr.on('data',()=>{});child.once('error',()=>{job.status='error';job.error='تعذر بدء محرك البث';job.process=null;});child.once('exit',code=>{job.process=null;if(job.status!=='stopping'){job.status='error';job.error='توقف المصدر أو تعذر تشغيله. تحقق من الرابط أو الملف.';onEvent('تعذر بث '+channel.name+': '+job.error,'warning');}});
 const deadline=Date.now()+20000;while(Date.now()<deadline&&job.process){if(fs.existsSync(path.join(folder,'index.m3u8'))){job.status='running';onEvent('بدأ بث القناة: '+channel.name,'success');return {msg:'ok',is_ok:true};}await new Promise(r=>setTimeout(r,250));}if(job.status==='error')throw fail(job.error,422);await stop(id);throw fail('لم تصل بيانات قابلة للبث خلال 20 ثانية',422);
 }
 function renderChannels(page='channels'){let s=fs.readFileSync(path.join(assets,'templates/admin/'+page+'.html'),'utf8');s=s.replace('{% include "admin/head.html" %}',fs.readFileSync(path.join(assets,'templates/admin/head.html'),'utf8')).replace('{% include "admin/footer.html" %}',fs.readFileSync(path.join(assets,'templates/admin/footer.html'),'utf8')).replace('{% include "admin/mnu.html" %}','<div class="header"><a href="/">مشاهدة القنوات</a> | <a href="/mubasher_admin/channels">التحكم بالقنوات</a> | <a href="/mubasher_admin/iptv">تحكم بـ IPTV</a> | <a href="/mubasher_admin/file">تحكم بالملفات</a> | <a href="/mubasher_admin/states">الإحصائيات</a><h2>البث المباشر — استراحة زين</h2></div>');s=s.replace(/<select name="cha_player"[\s\S]*?<\/select>/,'<select name="cha_player" id="cha_player"><option value="HTML5">HTML5 — تشغيل مباشر في المتصفح</option></select>');s=s.replace('عدد لانهائي من القنوات','قنواتك (أربع قنوات تعمل بالتزامن في الإعداد الحالي)');s=s.replace(/<select name="cha_src"[\s\S]*?<\/select>/,'<input name="cha_src" id="cha_src" dir="ltr" placeholder="http://... أو C:\\Videos\\movie.mp4" required>');s=s.replace(/<select name="cha_server_id"[\s\S]*?<\/select>/,'<select name="cha_server_id" id="cha_server_id"><option value="local">الخادم المحلي</option></select>');s=s.replace(/<div class="colasbmbtn" id="testDVRCurrent"[\s\S]*?<\/div>\s*<\/div>/,'');s=s.replace(/\{%[\s\S]*?%\}/g,'').replaceAll('{{admin_panel_path}}','mubasher_admin').replaceAll('{{admin_page}}',page).replaceAll('{{APP_VERSION}}','Zain');if(page==='channels'){const choices=[...state.iptv.map(r=>({name:r.iptv_name,source:r.iptv_link})),...state.file.map(r=>({name:r.file_name,source:r.file_path}))];s=s.replace('id="cha_src" dir=', 'id="cha_src" list="zain-sources" dir=');s=s.replace('</form>','<datalist id="zain-sources">'+choices.map(r=>'<option value="'+escape(r.source)+'">'+escape(r.name)+'</option>').join('')+'</datalist></form>');}s=s.replace('Mubasher By YeTech','البث المباشر — استراحة زين');return s.replace('</body>',`<script>$(document).ajaxError(function(e,x){var r=x.responseJSON;swal('تعذر تنفيذ العملية',r&&r.error||'تعذر الاتصال بالخادم','error')});</script></body>`);}
 function renderStats(){let s=renderChannels('states');const start=s.indexOf('<div class=" nopadding"'),end=s.indexOf('<div style="text-align: center;',start);if(start<0||end<0)throw Error('Statistics template changed');const day=new Date().toISOString().slice(0,10);const cards=state.channels.map(c=>{const v=stats[c.id]||{},live=jobs.get(c.id)?.status==='running';return '<div class="col-md-4 col-xs-12"><div class="tvcard"><div class="lightplace '+(live?'live':'nlive')+'"></div><div class="tvViews">'+(v.day===day?v.count||0:0)+'</div><div class="tvViews2">'+(v.total||0)+' جلسات مشاهدة كلية</div><div class="tvtext">'+escape(c.name)+'</div></div></div>';}).join('');return s.slice(0,start)+'<div class="page"><h3>إحصائيات البث</h3><p>عدد جلسات تشغيل البث بحسب الجهاز؛ اتصال متجدد بعد انقطاع دقيقة يُحسب جلسة جديدة.</p><div class="row">'+(cards||'<p>لا توجد قنوات حالياً</p>')+'</div></div>'+s.slice(end);}
 function html(res,s){s=require('./branding.cjs').html(s);res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}).end(s);}
 function sendFile(req,res,f,type){if(!fs.existsSync(f))throw fail('الملف غير موجود',404);res.writeHead(200,{'Content-Type':type,'Cache-Control':'no-store'});const stream=fs.createReadStream(f);stream.on('error',()=>res.destroy());res.on('close',()=>stream.destroy());if(req.method==='HEAD'){stream.destroy();res.end();}else stream.pipe(res);}
 const server=http.createServer(async(req,res)=>{const json=(v,s=200)=>res.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}).end(JSON.stringify(v));try{
 if(!allowedHost(req.headers.host,port))throw fail('Invalid host',403);const u=new URL(req.url,'http://'+req.headers.host),route=decodeURIComponent(u.pathname);res.setHeader('X-Content-Type-Options','nosniff');
 if(route==='/health')return json(status());
 if(route.startsWith('/mubasher_admin')){
  if(!authorize(req)){res.writeHead(302,{Location:'http://'+u.hostname+':'+mainPort+'/admin/sections'}).end();return;}
  const a=route.slice('/mubasher_admin'.length).split('/').filter(Boolean),action=a[0];
  if(action==='states')return html(res,renderStats());
  if(!action||['channels','iptv','file'].includes(action))return html(res,renderChannels(action||'channels'));
  if(action==='get'&&['iptv','file'].includes(a[1])){const rows=state[a[1]].map(row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[k,escape(v)])));return json({draw:Number(u.searchParams.get('draw'))||0,recordsTotal:rows.length,recordsFiltered:rows.length,data:rows});}
  if(action==='get')return json({draw:Number(u.searchParams.get('draw'))||0,recordsTotal:state.channels.length,recordsFiltered:state.channels.length,data:state.channels.slice(Number(u.searchParams.get('start'))||0,(Number(u.searchParams.get('start'))||0)+Math.min(100,Number(u.searchParams.get('length'))||10)).map(c=>({id:c.id,cha_name:escape(c.name),cha_src:escape(c.source.replace(/:\/\/[^/@]+@/,'://***@')),cha_boot:c.boot,cha_player:'HTML5',cha_server_id:'local',cha_img:c.image||''}))});
  if(action==='getRunningTABLE')return json([...jobs].filter(([id,j])=>j.status==='running').map(([id])=>id));
  if(req.headers.origin!=='http://'+req.headers.host&&!(req.headers['sec-fetch-site']==='same-origin'&&(req.headers.referer||'').startsWith('http://'+req.headers.host+'/')))throw fail('Cross-origin change rejected',403);
  if(action==='save'&&['iptv','file'].includes(a[1])){if(req.method!=='POST')throw fail('طريقة طلب غير صالحة',405);const {fields:b}=await require('./multipart.cjs')(req),table=a[1],name=b[table+'_name'],source=b[table==='file'?'file_path':'iptv_link'];if(!name?.trim()||name.length>150)throw fail('الاسم مطلوب');validateSource(source);if(table==='file'&&!/^[A-Za-z]:[\\/]|^\\\\/.test(source))throw fail('اختر مسار ملف محلي أو مشاركة شبكة');const row={id:crypto.randomUUID(),[table+'_name']:name,[table==='file'?'file_path':'iptv_link']:source};if(table==='iptv')row.iptv_no_edit=b.iptv_no_edit||'no';save({...state,[table]:[...state[table],row]});return json({msg:'ok'});}
  if(action==='delete'&&['iptv','file'].includes(a[1])){save({...state,[a[1]]:state[a[1]].filter(r=>r.id!==a[2])});return json({msg:'ok'});}
  if(action==='saveChannel'){
if(req.method!=='POST')throw fail('طريقة طلب غير صالحة',405);const {fields:b,files}=await require('./multipart.cjs')(req);if(Object.keys(files).some(k=>k!=='cha_img'))throw fail('حقل رفع غير صالح');let image;const uploaded=files.cha_img;if(uploaded){const bytes=uploaded.bytes;let ext;if(bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))ext='png';else if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)ext='jpg';else if(bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP')ext='webp';if(!ext||bytes.length>8*1024*1024)throw fail('ارفع صورة PNG أو JPG أو WEBP أقل من 8 ميغابايت');image=crypto.randomUUID()+'.'+ext;fs.mkdirSync(path.join(base,'data/promotional-media'),{recursive:true});fs.writeFileSync(path.join(base,'data/promotional-media',image),bytes,{flag:'wx'});}if(!b.cha_name?.trim()||b.cha_name.length>150)throw fail('اسم القناة مطلوب');const channel={id:crypto.randomUUID(),name:b.cha_name.trim(),source:validateSource(b.cha_src),image,boot:b.cha_boot==='yes'?'yes':'no'};save({...state,channels:[...state.channels,channel]});return json({msg:'ok'});}
  if(action==='start_channel')return json(await start(a[1]));
  if(action==='stop_channel'){await stop(a[1]);return json({msg:'ok'});}
  if(action==='delete'&&a[1]==='channels'){await stop(a[2]);save({...state,channels:state.channels.filter(c=>c.id!==a[2])});return json({msg:'ok'});}
  throw fail('هذه الوظيفة لم تُربط بعد',501);
 }
 if(!['GET','HEAD'].includes(req.method))throw fail('طريقة طلب غير صالحة',405);
 if(route.startsWith('/getChannelImg/')){const c=state.channels.find(c=>c.id===route.slice('/getChannelImg/'.length));if(!c?.image||!/^[-a-f0-9]+\.(png|jpg|webp)$/.test(c.image))throw fail('صورة غير موجودة',404);return sendFile(req,res,path.join(base,'data/promotional-media',c.image),'image/'+(c.image.endsWith('.jpg')?'jpeg':path.extname(c.image).slice(1)));}
 if(route.startsWith('/stream/')){const [, ,id,name]=route.split('/'),job=jobs.get(id);if(!job||!['index.m3u8'].includes(name)&&!/^segment-\d+\.ts$/.test(name||''))throw fail('البث غير متاح',404);if(name==='index.m3u8'&&req.method==='GET'&&fs.existsSync(path.join(job.folder,name)))trackViewer(req,id);return sendFile(req,res,path.join(job.folder,name),name.endsWith('.m3u8')?'application/vnd.apple.mpegurl':'video/mp2t');}
 if(/^\/(css|js|imgs|players)\//.test(route)){const root=path.resolve(assets,'static_files'),file=path.resolve(root,'.'+route);if(!file.startsWith(root+path.sep))throw fail('Invalid path',403);return sendFile(req,res,file,({'.css':'text/css','.js':'text/javascript','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.woff':'font/woff','.ttf':'font/ttf'})[path.extname(file)]||'application/octet-stream');}
 if(route.startsWith('/channel/')){const id=route.slice(9),c=state.channels.find(c=>c.id===id);if(!c)throw fail('القناة غير موجودة',404);return html(res,'<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><title>'+escape(c.name)+'</title><h1>'+escape(c.name)+'</h1><video id="video" controls autoplay style="width:95%;max-height:80vh"></video><p id="error"></p><script src="/players/js/hls.min.js"></script><script>var v=document.getElementById("video"),src='+JSON.stringify('/stream/'+id+'/index.m3u8')+';if(window.Hls&&Hls.isSupported()){var h=new Hls();h.loadSource(src);h.attachMedia(v);h.on(Hls.Events.ERROR,function(e,d){if(d.fatal)document.getElementById("error").textContent="البث غير متاح حالياً"})}else v.src=src;</script></html>');}
 if(route==='/')return html(res,'<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><title>البث المباشر</title><link rel="stylesheet" href="/css/style.css"><h1>البث المباشر — استراحة زين</h1><a href="/mubasher_admin">إدارة القنوات</a><ul>'+state.channels.map(c=>'<li><a href="/channel/'+c.id+'">'+escape(c.name)+'</a> — '+(jobs.get(c.id)?.status==='running'?'تعمل':'متوقفة')+'</li>').join('')+'</ul></html>');throw fail('غير موجود',404);
 }catch(e){if(!res.headersSent)json({msg:'error',error:e.message},e.status||500);else res.destroy();}});
 function status(){return {service:'zain-broadcast',port,listening,error,channels:state.channels.length,running:[...jobs.values()].filter(j=>j.status==='running').length};}
 server.on('error',e=>{error=e.code==='EADDRINUSE'?'منفذ البث مستخدم من برنامج آخر':e.message;});server.listen(port,'0.0.0.0',()=>{listening=true;for(const c of state.channels.filter(c=>c.boot==='yes'))start(c.id).catch(()=>{});});
 return {status,start,stop,close:async()=>{for(const id of [...jobs.keys()])await stop(id);server.close();server.closeAllConnections();listening=false;}};
};
