'use strict';
// The cafe catalogue has one durable SQLite home. Legacy files are import sources only.
const fs=require('node:fs'),path=require('node:path'),v8=require('node:v8');
const {DatabaseSync}=require('node:sqlite');
const families=['items','children','sectionItems','files','byMediaPath','byFilePath','scannedAliases'];
const clone=value=>value instanceof Set?new Set(value):value;
module.exports=function(base){
 const file=path.join(base,'data','catalog.sqlite');
 function open(){fs.mkdirSync(path.dirname(file),{recursive:true});const db=new DatabaseSync(file);db.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS catalog_meta(key TEXT PRIMARY KEY,value BLOB NOT NULL); CREATE TABLE IF NOT EXISTS catalog_maps(name TEXT NOT NULL,key TEXT NOT NULL,value BLOB NOT NULL,PRIMARY KEY(name,key)); CREATE INDEX IF NOT EXISTS catalog_maps_name ON catalog_maps(name); CREATE TABLE IF NOT EXISTS records (id TEXT PRIMARY KEY,payload TEXT NOT NULL,updated_at INTEGER NOT NULL);');require('./catalog-revision.cjs').initialize(db);require('./shared-scan-store.cjs').initialize(db);return db;}
 function read(){const db=open();try{const marker=db.prepare('SELECT value FROM catalog_meta WHERE key=?').get('snapshot');if(!marker)return null;const value={};for(const name of families){const map=new Map();for(const row of db.prepare('SELECT key,value FROM catalog_maps WHERE name=? ORDER BY rowid').iterate(name))map.set(row.key,v8.deserialize(row.value));value[name]=map;}return value;}finally{db.close();}}
 function write(value){const db=open();try{db.exec('BEGIN IMMEDIATE');db.prepare('DELETE FROM catalog_maps').run();const put=db.prepare('INSERT INTO catalog_maps(name,key,value) VALUES (?,?,?)');for(const name of families)for(const [key,row]of value[name])put.run(name,String(key),v8.serialize(clone(row)));db.prepare('INSERT INTO catalog_meta(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run('snapshot',Buffer.from(JSON.stringify({schema:1,createdAt:new Date().toISOString()})));db.exec('COMMIT');return true;}catch(error){try{db.exec('ROLLBACK')}catch{}throw error;}finally{db.close();}}
 function importLegacy(){const old=path.join(base,'data','sync-items.sqlite');if(!fs.existsSync(old))return false;const source=new DatabaseSync(old,{readOnly:true}),db=open();try{const names=['records','shared_scan_payloads','movie_scans'];db.exec('BEGIN IMMEDIATE');for(const name of names){const present=source.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(name);if(!present)continue;const columns=source.prepare('PRAGMA table_info('+name+')').all().map(row=>row.name);if(!columns.length)continue;const marks=columns.map(()=>'?').join(','),put=db.prepare('INSERT OR REPLACE INTO '+name+'('+columns.join(',')+') VALUES ('+marks+')');for(const row of source.prepare('SELECT * FROM '+name).iterate())put.run(...columns.map(column=>row[column]));}db.exec('COMMIT');return true;}catch(error){try{db.exec('ROLLBACK')}catch{}throw error;}finally{source.close();db.close();}}
function readState(key){const db=open();try{const row=db.prepare('SELECT value FROM catalog_meta WHERE key=?').get('state:'+key);return row?JSON.parse(Buffer.from(row.value).toString('utf8')):undefined;}finally{db.close();}}
 function writeState(key,value,history=false){const db=open();try{db.exec('CREATE TABLE IF NOT EXISTS catalog_state_history(key TEXT NOT NULL,at INTEGER NOT NULL,value BLOB NOT NULL,PRIMARY KEY(key,at))');db.exec('BEGIN IMMEDIATE');const payload=Buffer.from(JSON.stringify(value));if(history)db.prepare('INSERT OR REPLACE INTO catalog_state_history VALUES (?,?,?)').run(key,Date.now(),payload);db.prepare('INSERT INTO catalog_meta(key,value) VALUES (?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run('state:'+key,payload);db.exec('COMMIT');}catch(error){try{db.exec('ROLLBACK')}catch{}throw error;}finally{db.close();}}
 return {file,read,write,importLegacy,readState,writeState};
};
