'use strict';
const normalize=v=>String(v??'').normalize('NFKC').toLowerCase().replace(/[\u064b-\u065f\u0670\u0640]/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const groups=[['حركة','أكشن','action','28'],['مغامرة','مغامرات','adventure','12'],['انميشن','أنيميشن','رسوم متحركة','animation','16'],['كوميديا','comedy','35'],['جريمة','crime','80'],['وثائقي','وثائقية','documentary','99'],['دراما','drama','18'],['عائلي','عائلة','family','10751'],['خيال','فانتازيا','fantasy','14'],['تاريخي','تاريخ','history','36'],['رعب','ذعر','horror','27'],['موسيقي','موسيقى','music','10402'],['غموض','mystery','9648'],['رومانسي','رومانس','رومانسية','romance','10749'],['خيال علمي','science fiction','sci fi','878'],['إثارة','تشويق','thriller','53'],['حرب','حربي','war','10752'],['غربي','western','37'],['واقعية','واقع','reality','10764'],['سيرة ذاتية','biography'],['رياضي','رياضة','sport','sports'],['أطفال','kids','10762'],['أخبار','news','10763'],['حواري','talk','10767'],['مسلسل طويل','soap','10766'],['فيلم تلفزيوني','tv movie','10770']];
const aliases=new Map();for(const group of groups)for(const value of group)aliases.set(normalize(value),group[0]);
function names(value){if(value==null)return [];if(Array.isArray(value))return value.flatMap(names);if(typeof value==='object')return names(value.name||value.id);if(typeof value==='string'){try{const parsed=JSON.parse(value);if(Array.isArray(parsed))return names(parsed)}catch{}}const n=normalize(value);if(['action adventure','حركه ومغامره','حركه مغامره','10759'].includes(n))return ['حركة','مغامرة'];if(['sci fi fantasy','خيال علمي وفانتازيا','خيال علمي وخيال','10765'].includes(n))return ['خيال علمي','خيال'];if(['war politics','حرب وسياسه','10768'].includes(n))return ['حرب','سياسة'];return String(value).split(/[,،|;/]/).map(v=>aliases.get(normalize(v))||v.trim()).filter(v=>v&&!['null','undefined','all','الكل'].includes(v));}
function genres(item){let data=item.content?.contentJSON||{};if(typeof data==='string'){try{data=JSON.parse(data)}catch{data={}}}return [...new Set(['tagsArabic','tagsEnglish','genres','genre','Genre','genre_ids'].flatMap(k=>names(data[k])).concat(names(item.content?.genres)))];}
function matches(item,wanted){const query=names(wanted).map(normalize),available=new Set(genres(item).map(normalize));return !query.length||query.some(v=>available.has(v));}
module.exports={genres,matches,names};

